// Bundler: sharded data/ rows → gen/catalog.yaml, the ONE root object
// linkml-sqldb dumps. The slot→dir mapping is READ from the Catalog class —
// each bundle slot's range names a class, and that class's sql_table names its
// data dir. Adding a table to the container is the only edit.
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { parse, stringify } from 'yaml'

const at = (p: string) => fileURLToPath(new URL(p, import.meta.url))

const schema = parse(readFileSync(at('linkml/nodeve.yaml'), 'utf8'))
const classes: Record<string, { annotations?: { sql_table?: string } }> = schema.classes
const container = classes.Catalog?.attributes as Record<string, { range: string }> | undefined
if (!container) throw new Error('nodeve.yaml: no Catalog container class')

const bundle: Record<string, unknown[]> = {}
for (const [slot, { range }] of Object.entries(container)) {
  const dir = classes[range]?.annotations?.sql_table
  if (!dir) throw new Error(`Catalog.${slot}: range ${range} has no sql_table annotation`)
  bundle[slot] = readdirSync(at(`data/${dir}`))
    .filter((f) => f.endsWith('.yaml'))
    .sort()
    .map((f) => parse(readFileSync(at(`data/${dir}/${f}`), 'utf8')))
}

mkdirSync(at('gen'), { recursive: true })
writeFileSync(
  at('gen/catalog.yaml'),
  '# GENERATED by bundle.ts from data/ — the ingest root, not a source.\n' +
    stringify(bundle, { lineWidth: 0 }),
)
console.log(
  Object.entries(bundle)
    .map(([k, v]) => `${v.length} ${k}`)
    .join(', ') + ' → gen/catalog.yaml',
)
