// The enumeration/vocab emit for `pnpm generate`: read each concepts/enumeration/<name>/
// dir into its merged member-data dict, and render the TS vocab modules a code consumer imports.
// DATA FIRST — the .json is the wire shape (snake_case); the .ts vocab modules camelCase on top.
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { isPlainObject } from 'remeda';
import { join } from 'node:path';
import { parse as parseYaml } from 'yaml';
import humps from 'remeda-humps';
import { ENUMERATION_DIR } from '../src/concept-sources.ts';
import { renderJson } from './json-schema.ts';

/** One enumeration's `code → member data` dict from its enumeration/<name>/*.yaml files (`code` =
 *  file stem = the literal; `_defaults.yaml` is the cascade, merged then stripped of the filing
 *  selector). Snake_case — the wire shape the data file emits; the TS vocab modules camelCase on top. */
export function enumerationMemberData(name: string): Record<string, unknown> {
	const dir = join(ENUMERATION_DIR, name);
	const files = readdirSync(dir).filter((f) => f.endsWith('.yaml'));
	const defaults = files.includes('_defaults.yaml')
		? ((parseYaml(readFileSync(join(dir, '_defaults.yaml'), 'utf8')) ?? {}) as Record<string, unknown>)
		: {};
	const out: Record<string, unknown> = {};
	for (const file of files.filter((f) => f !== '_defaults.yaml').sort()) {
		const code = file.slice(0, -'.yaml'.length);
		const doc = { ...defaults, ...((parseYaml(readFileSync(join(dir, file), 'utf8')) ?? {}) as Record<string, unknown>) };
		// `identity` is real member data (symbol, url, iri_template, broader). Strip only the filing
		// SELECTOR: `archetype` (the schema selector — compiler plumbing) and the reserved `id` (DB uuid).
		if (isPlainObject(doc.identity)) {
			const identity = { ...doc.identity };
			delete identity.archetype;
			delete identity.id;
			if (Object.keys(identity).length > 0) doc.identity = identity;
			else delete doc.identity;
		}
		delete doc.feature; // compile plumbing (the prop field binding), not member data
		delete doc.schema;
		out[code] = doc;
	}
	return out;
}

/** Every enumeration dir, tree-driven — each emits a data file, no fixed list. */
export const enumerations = (): string[] =>
	readdirSync(ENUMERATION_DIR)
		.filter((name) => statSync(join(ENUMERATION_DIR, name)).isDirectory())
		.sort();

/** camelCase `code → Term` dict for a TS vocab module. */
function vocabDict(name: string): Record<string, unknown> {
	const out: Record<string, unknown> = {};
	for (const [code, doc] of Object.entries(enumerationMemberData(name))) out[code] = humps({ code, ...(doc as Record<string, unknown>) });
	return out;
}

/** An enumeration's generated TS vocab module — the `.ts` twin of its `.json`, matching the catalog
 *  and archetype emit: the member dict is the module `export default`, `as const` for the literal
 *  member-code union typed consumers branch on. Keyed by `code` = source file stem; no name to pick. */
export const renderVocabModule = (name: string): string =>
	[
		`// GENERATED by \`pnpm generate\` from concepts/enumeration/${name}/*.yaml. Do not edit by hand —`,
		'// edit the YAML and regenerate. The `export default` is the member dict (camelCase, keyed by',
		'// `code` = source file stem), `as const` for the literal member-code union consumers branch on.',
		'',
		`export default ${renderJson(vocabDict(name)).trimEnd()} as const;`,
		'',
	].join('\n');
