// The catalog slice of `pnpm generate`: the cascade-merged entries and their two emitted grains —
// artifacts/catalog/<slug>.json for JSON readers, src/generated/catalog/<slug>.ts (+ index.ts) for
// the fs-free JS/TS reader path (src/catalog.ts keys the composed array by identity).

import humps from 'remeda-humps';
import { camelizeSchema } from '@nodeve/schema-case';
import { shortCode } from '@nodeve/encoding/short-code';
import { effectiveSlug, loadCascade } from '../src/cascade.ts';
import { CATALOG_DIR } from '../src/concept-sources.ts';
import { assertDocValid, assertMetaSchema } from './validate-docs.ts';
import { backfillRegisterSpecNodes, resolveRepeatedFeatures } from './repeated-emit.ts';
import { renderHoistedConst } from './hoist.ts';

export interface CatalogEntryJson {
	identity: { archetype: string; slug: string; code: string };
	aliases?: string[];
	[key: string]: unknown;
}

/** The cascade-merged catalog, snake_case and enveloped, keyed by SLUG (globally unique across
 *  archetypes — a collision is an authoring error). Everything identifying lives under
 *  `identity`: `archetype` + `slug` + `code` (AUTHORED short-code minted at entry creation — the
 *  stable reference consumers persist; it survives file moves and slug renames, so the emit
 *  never derives it); the filing path stays out of the emit. The authored `archetype` selector
 *  may sit top-level or under `identity.archetype` (both forms); the emit canonicalizes.
 *  The emit gate itself (assertDocValid + the leaf/feature sweeps) lives in kit/validate-docs.ts. */
export function catalogEntries(): Record<string, CatalogEntryJson> {
	const out: Record<string, CatalogEntryJson> = {};
	const claimed = new Map<string, string>(); // slug -> path that claimed it
	const claimedByCode = new Map<string, string>(); // code -> path that claimed it (authored, so dupes possible)
	for (const leaf of loadCascade(CATALOG_DIR)) {
		const identity = (leaf.data.identity ?? {}) as Record<string, unknown>;
		const archetype = typeof identity.archetype === 'string' ? identity.archetype : leaf.archetype;
		// `settings_schema` is the ONE sanctioned break from "an archetype assembles features": a device
		// declares its commissioning knobs as a RAW JSON-schema (its own `required`/`properties`), not a
		// modelled feature. Lift it out before the archetype check (whose additionalProperties:false would
		// reject it), meta-validate it is a real schema, and let it flow verbatim into the emitted entry.
		const { settings_schema, ...forSchema } = leaf.data as Record<string, unknown>;
		if (settings_schema !== undefined) assertMetaSchema(leaf.path, settings_schema);
		assertDocValid(`catalog ${leaf.path}`, archetype, forSchema);
		const slug = effectiveSlug(leaf.path, identity);
		const prior = claimed.get(slug);
		if (prior) throw new Error(`grimoire catalog: slug "${slug}" is claimed by both ${prior} and ${leaf.path}`);
		claimed.set(slug, leaf.path);
		const code = identity.code;
		if (typeof code !== 'string')
			throw new Error(
				`grimoire catalog ${leaf.path}: no identity.code — mint one at creation and author it (suggested: ${shortCode(slug)})`,
			);
		const priorCode = claimedByCode.get(code);
		if (priorCode) throw new Error(`grimoire catalog: code "${code}" is claimed by both ${priorCode} and ${leaf.path}`);
		claimedByCode.set(code, leaf.path);
		const aliases = leaf.aliases === undefined ? {} : { aliases: leaf.aliases as string[] };
		// snake_case verbatim — JSON emits keep the wire casing; camelCase exists only in TS emits.
		const resolved = resolveRepeatedFeatures(leaf.data);
		backfillRegisterSpecNodes(resolved); // every LINKED modbus register must land on a spec node (its quantity)
		out[slug] = {
			...aliases,
			...resolved,
			identity: { archetype, slug, code },
		};
	}
	return out;
}

/** A catalog entry's own module: the one entry as a literal const — pure code (no fs, no JSON
 *  import), the isolated part catalog/index.ts composes. The <slug>.json twin serves JSON readers. */
const entryLocal = (slug: string): string => (/^[0-9]/.test(slug) ? `_${slug}` : slug);

/** The TS spelling of an entry: every KEY camelized deep (humps — values, slugs, codes untouched),
 *  the .json twin keeping the snake wire shape. `settings_schema` is the exception: a RAW JSON
 *  schema whose `properties`/`required` name snake wire settings — @nodeve/schema-case camelizes it
 *  AS a schema (`x-key-map` stamped), so it still validates wire data renamed at the parse edge. */
function camelizeEntry(entry: CatalogEntryJson): unknown {
	const { settings_schema, ...rest } = entry;
	return {
		...(humps(rest) as Record<string, unknown>),
		...(settings_schema === undefined ? {} : { settingsSchema: camelizeSchema(settings_schema) }),
	};
}

export const renderCatalogEntry = (entry: CatalogEntryJson): string =>
	'// GENERATED by `pnpm generate` — one catalog entry as the module default, composed into\n' +
	'// catalog/index.ts (camelCase keys — the snake wire shape is the <slug>.json twin). A repeated-\n' +
	'// feature spec the emit fills into every part (the authored `default`) is lifted to one `_sN`\n' +
	'// const and referenced per part. Do not edit by hand — edit the YAML, regenerate.\n\n' +
	renderHoistedConst(camelizeEntry(entry));

/** The catalog reader's module: composes the per-slug entry modules into one array — pure code (no
 *  fs, no JSON import), so it bundles serverless; kit/catalog.ts keys it by identity. Each entry is
 *  the module's `default`; the local alias here is filing only (the identity keys the map). */
export const renderCatalogIndex = (slugs: string[]): string =>
	'// GENERATED by `pnpm generate` — composes every per-slug catalog module into one array, keyed by\n' +
	'// identity (archetype + slug) by kit/catalog.ts. Do not edit by hand — edit the YAML, regenerate.\n\n' +
	slugs.map((s) => `import ${entryLocal(s)} from './${s}.ts';`).join('\n') +
	'\n\n' +
	`export const catalogEntries = [\n${slugs.map((s) => `\t${entryLocal(s)},`).join('\n')}\n] as const;\n`;
