// The aggregate-index emits of `pnpm generate` — the opt-in all-concepts modules over the
// per-concept emits (kit/emit-types.ts). Keys are camelized slugs like every generated TS surface;
// a wire (snake) slug renames at the lookup edge (src/validate-site.ts).

import { toCamelCase } from 'remeda';
import { pascal } from './emit-types.ts';

/** generated/archetype-index.ts: camelized slug → the AUTHORED data tree for every archetype-layer
 *  concept — the runtime aggregate the browse API (src/browse.ts) walks into archetype/feature/prop
 *  views. Data-only (no schema import): a browsing consumer wants labels, not validators. */
export function renderArchetypeIndex(concepts: Array<{ name: string; layer: string }>): string {
	const archetypes = concepts.filter((c) => c.layer === 'archetypes').sort((a, b) => a.name.localeCompare(b.name));
	return [
		'// GENERATED by `pnpm generate` — camelized slug → authored data tree, archetype layer only.',
		'// Do not edit by hand — edit the YAML and regenerate. The runtime aggregate the browse',
		"// API (src/browse.ts) reads; each value is the sibling module's data default (no fs, no JSON).",
		'',
		"import type { ArchetypeData } from '../browse-types.ts';",
		archetypes.map((c) => `import ${pascal(c.name)}Data from './archetypes/${c.name}.ts';`).join('\n'),
		'',
		"/** camelized slug → the archetype's authored data tree (title/description/prop slots). */",
		`export const archetypeData: Record<string, ArchetypeData> = {\n${archetypes.map((c) => `\t${toCamelCase(c.name)}: ${pascal(c.name)}Data,`).join('\n')}\n};`,
		'',
	].join('\n');
}

/** generated/index.ts: the runtime schema map + camelized-slug→type dict, built from per-concept
 *  imports. All imports are code (no `with { type: 'json' }`) — fs-free at runtime. Single-concept
 *  access goes to that concept's own module, not through here. */
export function renderConceptsIndex(concepts: Array<{ name: string; layer: string }>): string {
	const sorted = [...concepts].sort((a, b) => a.name.localeCompare(b.name));
	const tsPath = (c: { name: string; layer: string }): string => `./${c.layer}/${c.name}.ts`;
	return [
		'// GENERATED by `pnpm generate` — the aggregate over every per-concept module.',
		'// Do not edit by hand — edit the YAML and regenerate. This builds the runtime schema map and',
		'// camelized-slug→type dict; for a single concept import its own module. All imports are code, no JSON.',
		'',
		"import type { TSchema } from '@sinclair/typebox';",
		sorted.map((c) => `import { ${pascal(c.name)}Schema, type ${pascal(c.name)} } from '${tsPath(c)}';`).join('\n'),
		'',
		'/** Every compiled concept schema (live TypeBox), keyed by camelized slug — the runtime source',
		' *  (no fs); rename a wire slug at the lookup edge (src/validate-site.ts). Explicitly typed',
		' *  `Record<keyof ConceptTypes, TSchema>` — the inferred union is too large for TS to serialize',
		' *  (TS7056); per-concept modules keep their precise schema type. */',
		`export const conceptSchema: Record<keyof ConceptTypes, TSchema> = {\n${sorted.map((c) => `\t${toCamelCase(c.name)}: ${pascal(c.name)}Schema,`).join('\n')}\n};`,
		'',
		'/** camelized slug → parsed (camelCase) type — what a generic parse over `conceptSchema` keys on. */',
		`export interface ConceptTypes {\n${sorted.map((c) => `\t${toCamelCase(c.name)}: ${pascal(c.name)};`).join('\n')}\n}`,
		'',
	].join('\n');
}
