// The aggregate-index emits of `pnpm generate` — the opt-in all-concepts modules over the
// per-concept emits (kit/emit-types.ts). Keys are camelized slugs like every generated TS surface;
// a wire (snake) slug renames at the lookup edge (src/validate-site.ts).

import { toCamelCase } from 'remeda';
import { pascal } from './emit-types.ts';

/** generated/<layer>.ts: camelized slug → the layer's AUTHORED data trees — the opt-in aggregate
 *  that answers "list the layer" (`Object.keys`) and hands each concept's data tree. A root-level
 *  sibling of the layer dir, NOT `<layer>/index.ts` — a concept may itself be named `index`
 *  (property/index.ts is one). Data-only (no schema import): a browsing consumer wants labels,
 *  not validators — schemas live in `conceptSchema` (generated/index.ts) or each concept's own module. */
export function renderLayerIndex(layer: string, names: readonly string[]): string {
	const sorted = [...names].sort();
	const constName = toCamelCase(layer.replace(/s$/, ''));
	return [
		`// GENERATED by \`pnpm generate\` — camelized slug → authored data tree, ${layer} layer only.`,
		'// Do not edit by hand — edit the YAML and regenerate. The opt-in layer aggregate:',
		"// `Object.keys` lists the layer; each value is the sibling module's data default (no fs, no JSON).",
		'',
		sorted.map((n) => `import ${pascal(n)}Data from './${layer}/${n}.ts';`).join('\n'),
		'',
		`/** camelized slug → the ${constName}'s authored data tree (title/description/slots). */`,
		`export const ${constName} = {\n${sorted.map((n) => `\t${toCamelCase(n)}: ${pascal(n)}Data,`).join('\n')}\n};`,
		'',
	].join('\n');
}

/** generated/index.ts: the runtime schema map + camelized-slug→type dict, built from per-concept
 *  imports. All imports are code (no `with { type: 'json' }`) — fs-free at runtime. Single-concept
 *  access goes to that concept's own module, not through here. */
export function renderConceptsIndex(concepts: Array<{ name: string; layer: string }>): string {
	const sorted = [...concepts].sort((a, b) => a.name.localeCompare(b.name));
	const tsPath = (c: { name: string; layer: string }): string => `./${c.layer}/${c.name}.ts`;
	return [
		'// GENERATED by `pnpm generate` — the aggregate over every per-concept module.',
		'// Do not edit by hand — edit the YAML and regenerate. This builds the runtime schema map and',
		'// camelized-slug→type dict; for a single concept import its own module. All imports are code, no JSON.',
		'',
		"import type { TSchema } from '@sinclair/typebox';",
		sorted.map((c) => `import { ${pascal(c.name)}Schema, type ${pascal(c.name)} } from '${tsPath(c)}';`).join('\n'),
		'',
		'/** Every compiled concept schema (live TypeBox), keyed by camelized slug — the runtime source',
		' *  (no fs); rename a wire slug at the lookup edge (src/validate-site.ts). Explicitly typed',
		' *  `Record<keyof ConceptTypes, TSchema>` — the inferred union is too large for TS to serialize',
		' *  (TS7056); per-concept modules keep their precise schema type. */',
		`export const conceptSchema: Record<keyof ConceptTypes, TSchema> = {\n${sorted.map((c) => `\t${toCamelCase(c.name)}: ${pascal(c.name)}Schema,`).join('\n')}\n};`,
		'',
		'/** camelized slug → parsed (camelCase) type — what a generic parse over `conceptSchema` keys on. */',
		`export interface ConceptTypes {\n${sorted.map((c) => `\t${toCamelCase(c.name)}: ${pascal(c.name)};`).join('\n')}\n}`,
		'',
	].join('\n');
}
