// Codegen (`pnpm generate`): bake the runtime mirrors from the YAML sources so nothing on the
// runtime path — and nothing outside grimoire, ever — parses YAML. DATA FIRST, schemas
// are one projection. Two output roots, split by target, each mirroring concepts/ flat:
// src/generated/ (committed TS the runtime imports) and artifacts/ (gitignored JSON — the
// GitHub-release bundle for non-TS readers):
//   - artifacts/<layer>/<slug>.json — AUTHORED data tree per concept (title/description/ui/refs;
//     no `schema:` restatement); <slug>.schema.json — its draft-07 projection;
//     src/generated/<layer>/<slug>.ts — camelCase schema const + type + data default
//   - artifacts/enumeration/<name>.json — merged member docs (`schema:`/`feature:` plumbing
//     stripped), keyed by file stem (the literal); a src/generated/ `.ts` twin where a TS
//     consumer needs the member-code union
//   - artifacts/catalog/<slug>.json — one cascade-merged snake_case entry per item (repeated
//     features resolved to part.<name> / instances[n]; enveloped `identity: {archetype, slug,
//     code}`); no all-in-one — a JSON reader assembles its own bundle from the per-slug files
// Every catalog + property/enumeration leaf validates against its archetype's projected schema before
// anything emits — an invalid doc fails the whole generate (and the pre-commit that runs it).

import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { isPlainObject } from 'remeda';
import { dirname, join } from 'node:path';
import { parse as parseYaml } from 'yaml';
import humps from 'remeda-humps';
import { camelizeSchema } from '@nodeve/schema-case';
import { resolveConcept } from './compile.ts';
import { type RefContext, projectSchema } from './project.ts';
import {
	ARTIFACTS_DIR,
	GENERATED_DIR,
	type Obj,
	layerIndex,
	readYaml,
} from '../src/concept-sources.ts';
import {
	assertArchetypeDocsValid,
	assertFeatureDocsValid,
	assertLeafDocsValid,
} from './validate-docs.ts';
import { catalogEntries, renderCatalogEntry, renderCatalogIndex } from './emit-catalog.ts';
import { conceptDataTree, inlineSchemaOf, layerOf } from './data-tree.ts';
import { renderConceptsIndex, renderLayerIndex } from './emit-index.ts';
import { renderConceptModule } from './emit-types.ts';
import { enumerationMemberData, enumerations, renderVocabModule } from './emit-enumeration.ts';
import { renderJson } from './json-schema.ts';
import { parseDisplayPolicy } from '../src/display-policy.ts';

const DISPLAY_POLICY_YAML = join(import.meta.dirname, '..', 'display-policy', 'sensors.yaml');

// --- Concept schemas + types (consumer swap slice) ---

/** EVERY named concept compiled, keyed by slug in resolution order (features shadow archetypes — the same order kit/compile.ts resolves references). Tree-driven: the concepts/
 *  dirs are the only list, and ANY compile failure fails the whole generate (no silent skips). */
function compiledConcepts(): Array<{ name: string; data: Record<string, unknown>; layer: string }> {
	const out: Array<{ name: string; data: Record<string, unknown>; layer: string }> = [];
	const seen = new Set<string>();
	for (const layer of ['features', 'archetypes']) {
		for (const name of [...layerIndex(layer).keys()].sort()) {
			if (seen.has(name)) continue;
			seen.add(name);
			out.push({ name, data: resolveConcept(name), layer });
		}
	}
	return out;
}

// --- Emit ---

/** The display-policy reader's module: the authored sensors.yaml baked to one typed const — pure code
 *  (no fs, no YAML), so every consumer reads the policy through grimoire's API, never a file. */
const renderDisplayPolicyModule = (policy: unknown): string =>
	'// GENERATED by `pnpm generate` from display-policy/sensors.yaml — the authored display policy as\n' +
	'// one typed const. Do not edit by hand — edit the YAML, regenerate.\n\n' +
	"import type { DisplayPolicy } from '../display-policy.ts';\n\n" +
	`export const displayPolicy: DisplayPolicy = ${renderJson(policy).trimEnd()};\n`;

/** Rewrite kit/project.ts's bare `{$ref: <name>}` markers into draft-07 `#/$defs/<name>` pointers. */
function toJsonRefs(node: unknown): unknown {
	if (Array.isArray(node)) return node.map(toJsonRefs);
	if (!isPlainObject(node)) return node;
	if (typeof node.$ref === 'string') return { $ref: `#/$defs/${node.$ref}` };
	return Object.fromEntries(Object.entries(node).map(([k, v]) => [k, toJsonRefs(v)]));
}

/** The self-contained draft-07 schema for a concept: its ref-hoisted body plus a `$defs` block
 *  carrying every concept it (transitively) references, each itself ref-hoisted. */
function schemaWithDefs(data: Record<string, unknown>): {
	json: Obj;
	body: Obj;
	imports: Array<{ name: string; layer: string }>;
} {
	const deps = new Set<string>();
	const body = toJsonRefs(projectSchema(data, { schemaOf: inlineSchemaOf, deps })) as Obj;
	const direct = [...deps];
	const $defs: Obj = {};
	const queue = [...deps];
	while (queue.length > 0) {
		const name = queue.shift()!;
		if (name in $defs) continue;
		const sub: RefContext = { schemaOf: inlineSchemaOf, deps: new Set() };
		$defs[name] = toJsonRefs(projectSchema(resolveConcept(name), sub));
		for (const n of sub.deps) if (!(n in $defs)) queue.push(n);
	}
	// `json`: the self-contained draft-07 (refs resolve via `$defs`). `body`: the same minus `$defs`
	// — the .ts resolves each `$ref` through an imported sibling const, so a local `$defs` would only
	// re-inline (and re-bloat) the very shapes the refs exist to share.
	const json = { ...body, ...(Object.keys($defs).length > 0 ? { $defs } : {}) };
	return { json, body, imports: direct.map((name) => ({ name, layer: layerOf(name) })) };
}

const CLASS_OF: Record<string, string> = {
	archetypes: 'archetype',
	features: 'feature',
	property: 'property',
};

function stampIdentity(tree: Obj, name: string, layer: string): Obj {
	const authored = isPlainObject(tree.identity) ? (tree.identity as Obj) : {};
	return { ...tree, identity: { archetype_id: CLASS_OF[layer], slug: name, ...authored } };
}

function topFields(name: string): string[] {
	const { $composes, ...def } = resolveConcept(name);
	const layer = layerOf(name);
	const tree = humps(stampIdentity(conceptDataTree(def, layer, $composes), name, layer)) as Obj;
	const own = Object.keys(tree).filter((key) => key !== '$ref');
	const base =
		typeof tree.$ref === 'string'
			? topFields(
					tree.$ref
						.split('/')
						.pop()!
						.replace(/\.json$/, ''),
				)
			: [];
	return [...new Set([...base, ...own])];
}

function emitConcept(options: {
	out: Record<string, string>;
	name: string;
	data: Record<string, unknown>;
	layer: string;
}) {
	const { out, name, data, layer } = options;
	const { $composes, ...def } = data;
	const { json, body, imports } = schemaWithDefs(def);
	const dataTree = stampIdentity(conceptDataTree(def, layer, $composes), name, layer);
	out[join(ARTIFACTS_DIR, layer, `${name}.json`)] = renderJson(dataTree);
	out[join(GENERATED_DIR, layer, `${name}.ts`)] = renderConceptModule({
		name,
		schema: camelizeSchema(body) as Obj,
		layer,
		imports,
		data: humps(dataTree),
		fieldsOf: topFields,
	});
	out[join(ARTIFACTS_DIR, layer, `${name}.schema.json`)] = renderJson(json);
	out[join(ARTIFACTS_DIR, layer, `${name}.camel.schema.json`)] = renderJson(camelizeSchema(json));
	return imports;
}

function emitConcepts(out: Record<string, string>, concepts: ReturnType<typeof compiledConcepts>) {
	const queue: string[] = [];
	const queueProperties = (imports: Array<{ name: string; layer: string }>) => {
		for (const dependency of imports)
			if (dependency.layer === 'property') queue.push(dependency.name);
	};
	for (const concept of concepts) queueProperties(emitConcept({ out, ...concept }));
	const emitted = new Set<string>();
	while (queue.length > 0) {
		const name = queue.shift()!;
		if (emitted.has(name)) continue;
		emitted.add(name);
		queueProperties(emitConcept({ out, name, data: resolveConcept(name), layer: 'property' }));
	}
	return emitted;
}

function emitCatalog(out: Record<string, string>, entries: ReturnType<typeof catalogEntries>) {
	const slugs = Object.keys(entries).sort();
	for (const slug of slugs) {
		out[join(ARTIFACTS_DIR, 'catalog', `${slug}.json`)] = renderJson(entries[slug]);
		out[join(GENERATED_DIR, 'catalog', `${slug}.ts`)] = renderCatalogEntry(entries[slug]!);
	}
	out[join(GENERATED_DIR, 'catalog', 'index.ts')] = renderCatalogIndex(slugs);
}

export function outputs(): Record<string, string> {
	assertLeafDocsValid();
	assertFeatureDocsValid();
	assertArchetypeDocsValid();
	const entries = catalogEntries();
	const concepts = compiledConcepts();
	const out: Record<string, string> = {
		[join(GENERATED_DIR, 'index.ts')]: renderConceptsIndex(concepts),
	};
	// Per catalog entry, keyed by slug: the committed JSON grain a JSON reader assembles, and its
	// TS-const twin — the isolated part the JS/TS reader path imports (code, no fs/JSON import).
	emitCatalog(out, entries);
	// The JS/TS reader's grain: catalog/index.ts composes the per-slug modules into one array — code,
	// no fs/JSON import, so `loadDevice` bundles into a serverless build (kit/catalog.ts keys by identity).
	// One concept's sibling files (data .json, camelCase .ts, snake + camel draft-07 .schema.json),
	// the same layout every layer emits. Returns the direct concept refs so the caller can chase them.
	// - Ref-hoisted projection: each composed slot is a `$ref` (self-contained `$defs` in the .schema.json,
	//   a sibling `<Name>Schema` import in the .ts) — one shape defined once, not restated per use site.
	// - The data .json: the one-level-referential AUTHORED tree (labels, ui, refs — the schema lives
	//   once, in the sibling .schema.json, never restated here); a cold reader resolves each `$ref`
	//   across files itself, so the file never splices a nested concept in. The .ts data default is
	//   the same tree through remeda-humps — camelCase keys, TS's spelling wall-to-wall.
	// - BOTH casings are projections of the one snake draft-07, via @nodeve/schema-case: the TS module
	//   transcribes the camel sibling (x-key-map aliases in place); <name>.camel.schema.json is the same
	//   camel schema for JSON consumers ($defs keys / $ref targets are slugs — identity, so they stay).
	// The identity de-sugar on the EMIT side: every concept's data tree ships
	// `identity.{archetype, slug}` — archetype = the def's class (its layer), slug = the file stem —
	// authored identity keys (symbol/code/an explicit slug…) winning. The twin of the validation-side
	// de-sugar (kit/validate-docs.ts).
	// A concept's top-level data field names, its composed base's included (`$ref` chased through the
	// chain) — what renderConceptModule projects when a module's data composes a base at the top.
	// features + archetypes, collecting the property atoms they $ref so each gets its own module.
	const emittedProps = emitConcepts(out, concepts);
	// The referenced property atoms, transitively — the importable home a composer $refs instead of
	// inlining the field. A property NOT $ref'd (e.g. a bare part-instance name) emits no module.
	// Per-layer data aggregates: generated/<layer>/index.ts answers "list the layer" — published as
	// `@nodeve/grimoire/<layer>`, beside the per-concept `@nodeve/grimoire/<layer>/<slug>` subpaths.
	// A concept named `index` would clobber its layer's aggregate — refuse the bake outright.
	const clobber = [...concepts.map((c) => c.name), ...emittedProps].filter((n) => n === 'index');
	if (clobber.length > 0)
		throw new Error('a concept named "index" would clobber its layer aggregate — rename it');
	for (const layer of ['archetypes', 'features'])
		out[join(GENERATED_DIR, layer, 'index.ts')] = renderLayerIndex(
			layer,
			concepts.filter((c) => c.layer === layer).map((c) => c.name),
		);
	out[join(GENERATED_DIR, 'property', 'index.ts')] = renderLayerIndex('property', [
		...emittedProps,
	]);
	// Member data per enumeration — every enumeration, tree-driven: .json wire shape + .ts vocab twin.
	for (const name of enumerations()) {
		out[join(ARTIFACTS_DIR, 'enumeration', `${name}.json`)] = renderJson(
			enumerationMemberData(name),
		);
		out[join(GENERATED_DIR, 'enumeration', `${name}.ts`)] = renderVocabModule(name);
	}
	// TODO(move-display-policy): display-policy/ is a data source OUTSIDE concepts/ with its own
	// bespoke parse+emit — the one violation of "the generator reads only concepts/". Move it soon:
	// fold into the concept model (ui/display fields on the quantity enumerations) or evict
	// downstream; then guard generator inputs to concepts/ only.
	// The authored display policy: a typed const for TS consumers AND an artifacts JSON twin — a TS
	// export is a view of baked data, never the only copy (guard-artifacts-baked.ts).
	const policy = parseDisplayPolicy(parseYaml(readFileSync(DISPLAY_POLICY_YAML, 'utf8')));
	out[join(GENERATED_DIR, 'display-policy.ts')] = renderDisplayPolicyModule(policy);
	out[join(ARTIFACTS_DIR, 'display-policy.json')] = renderJson(policy);
	// Parts maps (concepts/parts/) — read by the repeated-feature resolve; baked so every YAML the
	// generator reads lands in artifacts/ as JSON.
	for (const [name, path] of [...layerIndex('parts')].sort(([a], [b]) => a.localeCompare(b)))
		out[join(ARTIFACTS_DIR, 'parts', `${name}.json`)] = renderJson(readYaml(path));
	return out;
}

// Write only when run directly, not when imported by the drift test.
if (import.meta.filename === process.argv[1]) {
	// Wipe both output roots first so no stale file (renamed/deleted concept) survives the bake.
	rmSync(GENERATED_DIR, { recursive: true, force: true });
	rmSync(ARTIFACTS_DIR, { recursive: true, force: true });
	const files = Object.entries(outputs());
	for (const [path, contents] of files) {
		mkdirSync(dirname(path), { recursive: true });
		writeFileSync(path, contents);
	}
	console.log(`grimoire: wrote ${files.length} files to src/generated + artifacts`);
}
