// Codegen (`pnpm generate`): bake the runtime mirrors from the YAML sources so nothing on the
// runtime path — and nothing outside grimoire, ever — parses YAML. DATA FIRST, schemas
// are one projection. Two output roots, split by target, each mirroring concepts/ flat:
// src/generated/ (committed TS the runtime imports) and artifacts/ (gitignored JSON — the
// GitHub-release bundle for non-TS readers):
//   - artifacts/<layer>/<slug>.json — AUTHORED data tree per concept (title/description/ui/refs;
//     no `schema:` restatement); <slug>.schema.json — its draft-07 projection;
//     src/generated/<layer>/<slug>.ts — camelCase schema const + type + data default
//   - artifacts/enumeration/<name>.json — merged member docs (`schema:`/`feature:` plumbing
//     stripped), keyed by file stem (the literal); a src/generated/ `.ts` twin where a TS
//     consumer needs the member-code union
//   - artifacts/catalog/<slug>.json — one cascade-merged snake_case entry per item (repeated
//     features resolved to part.<name> / instances[n]; enveloped `identity: {archetype, slug,
//     code}`); no all-in-one — a JSON reader assembles its own bundle from the per-slug files
// Every catalog + property/enumeration leaf validates against its archetype's projected schema before
// anything emits — an invalid doc fails the whole generate (and the pre-commit that runs it).

import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { isPlainObject } from 'remeda';
import { dirname, join } from 'node:path';
import { parse as parseYaml } from 'yaml';
import humps from 'remeda-humps';
import { camelizeSchema } from '@nodeve/schema-case';
import { resolveConcept } from './compile.ts';
import { type RefContext, projectSchema } from './project.ts';
import { type Obj, layerIndex } from '../src/concept-sources.ts';
import { assertFeatureDocsValid, assertLeafDocsValid } from './validate-docs.ts';
import { catalogEntries, renderCatalogEntry, renderCatalogIndex } from './emit-catalog.ts';
import { conceptDataTree, inlineSchemaOf, layerOf } from './data-tree.ts';
import { renderConceptsIndex, renderLayerIndex } from './emit-index.ts';
import { renderConceptModule } from './emit-types.ts';
import { enumerationMemberData, enumerations, renderVocabModule } from './emit-enumeration.ts';
import { renderJson } from './json-schema.ts';
import { parseDisplayPolicy } from '../src/display-policy.ts';

const ROOT = join(import.meta.dirname, '..');
const GENERATED = join(ROOT, 'src', 'generated');
const ARTIFACTS = join(ROOT, 'artifacts');
const DISPLAY_POLICY_YAML = join(ROOT, 'display-policy', 'sensors.yaml');

// --- Concept schemas + types (consumer swap slice) ---

/** EVERY named concept compiled, keyed by slug in resolution order (features shadow archetypes — the same order kit/compile.ts resolves references). Tree-driven: the concepts/
 *  dirs are the only list, and ANY compile failure fails the whole generate (no silent skips). */
function compiledConcepts(): Array<{ name: string; data: Record<string, unknown>; layer: string }> {
	const out: Array<{ name: string; data: Record<string, unknown>; layer: string }> = [];
	const seen = new Set<string>();
	for (const layer of ['features', 'archetypes']) {
		for (const name of [...layerIndex(layer).keys()].sort()) {
			if (seen.has(name)) continue;
			seen.add(name);
			out.push({ name, data: resolveConcept(name), layer });
		}
	}
	return out;
}

// --- Emit ---

/** The display-policy reader's module: the authored sensors.yaml baked to one typed const — pure code
 *  (no fs, no YAML), so every consumer reads the policy through grimoire's API, never a file. */
const renderDisplayPolicyModule = (policy: unknown): string =>
	'// GENERATED by `pnpm generate` from display-policy/sensors.yaml — the authored display policy as\n' +
	'// one typed const. Do not edit by hand — edit the YAML, regenerate.\n\n' +
	"import type { DisplayPolicy } from '../display-policy.ts';\n\n" +
	`export const displayPolicy: DisplayPolicy = ${renderJson(policy).trimEnd()};\n`;

/** Rewrite kit/project.ts's bare `{$ref: <name>}` markers into draft-07 `#/$defs/<name>` pointers. */
function toJsonRefs(node: unknown): unknown {
	if (Array.isArray(node)) return node.map(toJsonRefs);
	if (!isPlainObject(node)) return node;
	if (typeof node.$ref === 'string') return { $ref: `#/$defs/${node.$ref}` };
	return Object.fromEntries(Object.entries(node).map(([k, v]) => [k, toJsonRefs(v)]));
}

/** The self-contained draft-07 schema for a concept: its ref-hoisted body plus a `$defs` block
 *  carrying every concept it (transitively) references, each itself ref-hoisted. */
function schemaWithDefs(data: Record<string, unknown>): { json: Obj; body: Obj; imports: Array<{ name: string; layer: string }> } {
	const deps = new Set<string>();
	const body = toJsonRefs(projectSchema(data, { schemaOf: inlineSchemaOf, deps })) as Obj;
	const direct = [...deps];
	const $defs: Obj = {};
	const queue = [...deps];
	while (queue.length > 0) {
		const name = queue.shift()!;
		if (name in $defs) continue;
		const sub: RefContext = { schemaOf: inlineSchemaOf, deps: new Set() };
		$defs[name] = toJsonRefs(projectSchema(resolveConcept(name), sub));
		for (const n of sub.deps) if (!(n in $defs)) queue.push(n);
	}
	// `json`: the self-contained draft-07 (refs resolve via `$defs`). `body`: the same minus `$defs`
	// — the .ts resolves each `$ref` through an imported sibling const, so a local `$defs` would only
	// re-inline (and re-bloat) the very shapes the refs exist to share.
	const json = { ...body, ...(Object.keys($defs).length > 0 ? { $defs } : {}) };
	return { json, body, imports: direct.map((name) => ({ name, layer: layerOf(name) })) };
}

export function outputs(): Record<string, string> {
	assertLeafDocsValid();
	assertFeatureDocsValid();
	const entries = catalogEntries();
	const concepts = compiledConcepts();
	const out: Record<string, string> = {
		[join(GENERATED, 'index.ts')]: renderConceptsIndex(concepts),
	};
	// Per catalog entry, keyed by slug: the committed JSON grain a JSON reader assembles, and its
	// TS-const twin — the isolated part the JS/TS reader path imports (code, no fs/JSON import).
	const slugs = Object.keys(entries).sort();
	for (const slug of slugs) {
		out[join(ARTIFACTS, 'catalog', `${slug}.json`)] = renderJson(entries[slug]);
		out[join(GENERATED, 'catalog', `${slug}.ts`)] = renderCatalogEntry(entries[slug]!);
	}
	// The JS/TS reader's grain: catalog/index.ts composes the per-slug modules into one array — code,
	// no fs/JSON import, so `loadDevice` bundles into a serverless build (kit/catalog.ts keys by identity).
	out[join(GENERATED, 'catalog', 'index.ts')] = renderCatalogIndex(slugs);
	// One concept's sibling files (data .json, camelCase .ts, snake + camel draft-07 .schema.json),
	// the same layout every layer emits. Returns the direct concept refs so the caller can chase them.
	// - Ref-hoisted projection: each composed slot is a `$ref` (self-contained `$defs` in the .schema.json,
	//   a sibling `<Name>Schema` import in the .ts) — one shape defined once, not restated per use site.
	// - The data .json: the one-level-referential AUTHORED tree (labels, ui, refs — the schema lives
	//   once, in the sibling .schema.json, never restated here); a cold reader resolves each `$ref`
	//   across files itself, so the file never splices a nested concept in. The .ts data default is
	//   the same tree through remeda-humps — camelCase keys, TS's spelling wall-to-wall.
	// - BOTH casings are projections of the one snake draft-07, via @nodeve/schema-case: the TS module
	//   transcribes the camel sibling (x-key-map aliases in place); <name>.camel.schema.json is the same
	//   camel schema for JSON consumers ($defs keys / $ref targets are slugs — identity, so they stay).
	const emitConcept = (name: string, data: Record<string, unknown>, layer: string): Array<{ name: string; layer: string }> => {
		const { $composes, ...def } = data;
		const { json, body, imports } = schemaWithDefs(def);
		const dataTree = conceptDataTree(def, layer, $composes);
		out[join(ARTIFACTS, layer, `${name}.json`)] = renderJson(dataTree);
		out[join(GENERATED, layer, `${name}.ts`)] = renderConceptModule({ name, schema: camelizeSchema(body) as Obj, layer, imports, data: humps(dataTree) });
		out[join(ARTIFACTS, layer, `${name}.schema.json`)] = renderJson(json);
		out[join(ARTIFACTS, layer, `${name}.camel.schema.json`)] = renderJson(camelizeSchema(json));
		return imports;
	};
	// features + archetypes, collecting the property atoms they $ref so each gets its own module.
	const propQueue: string[] = [];
	const queueProps = (imports: Array<{ name: string; layer: string }>): void => {
		for (const d of imports) if (d.layer === 'property') propQueue.push(d.name);
	};
	for (const c of concepts) queueProps(emitConcept(c.name, c.data, c.layer));
	// The referenced property atoms, transitively — the importable home a composer $refs instead of
	// inlining the field. A property NOT $ref'd (e.g. a bare part-instance name) emits no module.
	const emittedProps = new Set<string>();
	while (propQueue.length > 0) {
		const name = propQueue.shift()!;
		if (emittedProps.has(name)) continue;
		emittedProps.add(name);
		queueProps(emitConcept(name, resolveConcept(name), 'property'));
	}
	// Per-layer data aggregates: generated/<layer>.ts answers "list the layer" — reachable to
	// consumers via the `./generated/*` subpath export, like every per-concept module.
	for (const layer of ['archetypes', 'features'])
		out[join(GENERATED, `${layer}.ts`)] = renderLayerIndex(layer, concepts.filter((c) => c.layer === layer).map((c) => c.name));
	out[join(GENERATED, 'property.ts')] = renderLayerIndex('property', [...emittedProps]);
	// Member data per enumeration — every enumeration, tree-driven: .json wire shape + .ts vocab twin.
	for (const name of enumerations()) {
		out[join(ARTIFACTS, 'enumeration', `${name}.json`)] = renderJson(enumerationMemberData(name));
		out[join(GENERATED, 'enumeration', `${name}.ts`)] = renderVocabModule(name);
	}
	// The authored display policy, baked to a typed const so every consumer reads it through the API.
	out[join(GENERATED, 'display-policy.ts')] = renderDisplayPolicyModule(
		parseDisplayPolicy(parseYaml(readFileSync(DISPLAY_POLICY_YAML, 'utf8'))),
	);
	return out;
}

// Write only when run directly, not when imported by the drift test.
if (import.meta.filename === process.argv[1]) {
	// Wipe both output roots first so no stale file (renamed/deleted concept) survives the bake.
	rmSync(GENERATED, { recursive: true, force: true });
	rmSync(ARTIFACTS, { recursive: true, force: true });
	for (const [path, contents] of Object.entries(outputs())) {
		mkdirSync(dirname(path), { recursive: true });
		writeFileSync(path, contents);
		console.log(`grimoire: wrote ${path}`);
	}
}
